# Generated by Django 5.2.3 on 2025-06-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layouts', '0002_rename_schema_reportlayout_layout_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='$', max_length=5)),
                ('change_percent', models.FloatField()),
                ('trend_data', models.JSONField()),
            ],
            bases=('layouts.basemodel',),
        ),
        migrations.CreateModel(
            name='BalanceSummary',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_type', models.CharField(max_length=10)),
                ('currency', models.CharField(default='$', max_length=5)),
            ],
            bases=('layouts.basemodel',),
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_in_percent', models.FloatField()),
                ('money_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_out_percent', models.FloatField()),
                ('currency', models.CharField(default='$', max_length=5)),
            ],
            bases=('layouts.basemodel',),
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goal_description', models.CharField(max_length=255)),
                ('achieved_status', models.BooleanField()),
                ('currency', models.CharField(default='$', max_length=5)),
            ],
            bases=('layouts.basemodel',),
        ),
        migrations.CreateModel(
            name='SpendActivity',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='$', max_length=5)),
            ],
            bases=('layouts.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layouts.basemodel')),
                ('date_time', models.DateTimeField()),
                ('merchant_name', models.CharField(max_length=100)),
                ('card_last_digits', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('currency', models.CharField(default='$', max_length=5)),
            ],
            bases=('layouts.basemodel',),
        ),
    ]
