# Generated by Django 5.2.3 on 2025-06-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlayout',
            old_name='schema',
            new_name='layout_schema',
        ),
    ]
